server:
  port: 8080

spring:
  application:
    name: auth-api
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth_service
  flyway:
    enabled: true
    schemas: auth_service

security:
  jwt:
    secret: ${JWT_SECRET}
    ttl-minutes: 30

app:
  internal-service:
    data-api-url: ${DATA_API_BASE_URL:http://data-api:8081}
    internal-token: ${INTERNAL_TOKEN}

